### ISSUE TITLE
Photos ready for review

### ISSUE THREAD

**Issue by jfeng702** [jfeng702/Slice#2]

**Comment by s-pangburn** [comment]
- [ ] Title and description should be bigger
- [ ] Edit and Delete buttons should be positioned more obviously so it's clear they are for the photo, not the comment
- [ ] I only see the Edit button right now?

**Comment by jfeng702** [comment]
Hi Stephen, 

These issues should be complete. Please let me know of any feedback. Thank you.

**Comment by s-pangburn** [comment]
- [ ] My photo edits don't persist to the database. I refresh the page and the title/description reverts to what it originally was

**Comment by s-pangburn** [comment]
🙌
