### ISSUE TITLE
readme complete and ready for review

### ISSUE THREAD

**Issue by jfeng702** [jfeng702/Slice#5]

**Comment by s-pangburn** [comment]
Hey Joey! Definitely include a screen clipping or two to show off what your site looks like. There should be a visual component to your README for people skimming through.

**Comment by jfeng702** [comment]
I have included a gif and a screen grab, let me know your thoughts. Thanks Stephen!

**Comment by s-pangburn** [comment]
The gif ends too early imo, which makes it a little jarring to look at, but that's not a critical issue or anything. I can sign off on this 🙂

**Comment by s-pangburn** [comment]
Be sure to come back to this later and add more content when you've added albums and tags!

**Comment by jfeng702** [comment]
thanks for the feedback. i uploaded a new gif that shows the entire comment
edit process.

**Comment by s-pangburn** [comment]
Awesome! 👏  Great work Joey!
